### ISSUE TITLE
Updating 1.5.0 to 1.5.2 crashes the game with Biomes O' Plenty and Embeddium

### ISSUE THREAD

**Issue by MikroChris** [LieOnLion/MCV-BiomesOPlenty#3] opened 2024-04-22 04:15 UTC
I have installed the 1.5.0 MCV and the compat with Biomes O' Plenty, and also embeddium, and when I tried to oppen my world it crashes, idk why

I opened another world and it seems that the BOP chests cause the crash.
What happens is that if I have a chest from BOP with items in it and update the mod to higher versions it crashes when trying to load the world

**Comment by ketson-mc** [comment] 2024-04-25 09:29
i wouldnt mind joining the discord! is there a way to remove the addons at all?
I had posted this question on reddit too, and the answer i got was that the renderer was in the wrong file location. i hope that might be able to help :/ 
https://www.reddit.com/r/MinecraftHelp/comments/1cbmr6h/comment/l16cjs6/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by LieOnLion** [comment] 2024-04-26 17:07
Ik what the problem is, just working on new temporary textures.
Also now with 1.20.5 out I need more time to update everything.

**Comment by LieOnLion** [comment] 2024-06-03 07:05
fixed in latest beta version

**Closed by LieOnLion** 2024-06-03 07:05 UTC
